import React from 'react';
import { AlgorithmModule, AlgorithmMetric, InteractiveAlgorithmContext, Point } from '../types';

export interface RandomForestState {
  nEstimators: number;
  maxDepth: number;
  accuracy: number;
  singleTreeAccuracy: number;
  varianceReduction: number;
  treeSplits: { x?: number; y?: number; treeIndex: number; color: string }[];
}

export const randomForestModule: AlgorithmModule = {
  id: 'random_forest',
  name: 'Random Forest Ensemble',
  shortLabel: 'Random Forest',
  category: 'Ensemble Methods',
  badgeText: 'Bagging • Bootstrap Aggregation',
  badgeColor: 'bg-emerald-50 text-emerald-900 border-emerald-300',
  description: 'Trains an ensemble of decorrelated decision trees using bootstrap aggregation (bagging) and random feature subsets. Aggregates votes across all trees to dramatically slash variance and prevent overfitting.',

  simpleAnalogy: 'Wisdom of the crowd! If 1 doctor makes a diagnosis, they might have a bad day and misread a symptom. If you ask a committee of 20 doctors and take the majority vote, their individual quirks cancel out and the verdict is far more reliable!',
  simpleSteps: [
    'Bootstrap: Create multiple different subsets of the data by picking samples randomly with replacement.',
    'Grow Trees: Train an independent decision tree on each subset.',
    'Majority Vote: Let every tree vote on the prediction. The majority vote is the final decision!'
  ],
  whatToTry: [
    'Slide "Number of Trees (Estimators)" from 1 to 10. Notice how 1 tree produces harsh jagged cuts, while 5+ trees blend together into a much more natural, smoothed boundary!',
    'Toggle "Show Individual Tree Cuts" to see the faint multicolored split lines from each tree in the forest.',
    'Notice the "Variance Reduction" metric climb as you add more trees.'
  ],

  getHypothesisText: (params, state: RandomForestState) => {
    return `H(x) = mode{ h₁(x), h₂(x), ..., h_B(x) } • B=${state.nEstimators} Trees • Ensemble Acc: ${state.accuracy}% (+${state.varianceReduction}% vs 1 Tree)`;
  },

  parameters: [
    {
      id: 'nEstimators',
      label: 'Number of Trees in Forest (B)',
      type: 'slider',
      min: 1,
      max: 15,
      step: 2,
      defaultValue: 5,
      description: 'Total number of independent decision trees voting in the ensemble.',
      minLabel: '1 Tree (Noisy)',
      maxLabel: '15 Trees (Smooth Consensus)'
    },
    {
      id: 'maxDepth',
      label: 'Max Tree Depth',
      type: 'slider',
      min: 1,
      max: 4,
      step: 1,
      defaultValue: 2,
      description: 'Maximum hierarchical split depth allowed for any individual tree.',
      minLabel: '1 (Stumps)',
      maxLabel: '4 (Deep)'
    },
    {
      id: 'showIndividualTrees',
      label: 'Show Individual Tree Cuts',
      type: 'toggle',
      defaultValue: true,
      description: 'Displays the faint partition splits generated by individual trees in the forest.'
    },
    {
      id: 'showConsensusMap',
      label: 'Ensemble Consensus Shading',
      type: 'toggle',
      defaultValue: true,
      description: 'Shades regions where 80%+ of the trees agree on the prediction.'
    }
  ],

  getDefaultParameters: () => ({
    nEstimators: 5,
    maxDepth: 2,
    showIndividualTrees: true,
    showConsensusMap: true
  }),

  generateDataset: (sampleCount: number, noiseLevel: number) => {
    const points: Point[] = [];
    const n = Math.floor(sampleCount / 2);

    // Class 0: Clustered in top-left & bottom-right
    for (let i = 0; i < n; i++) {
      const isTopLeft = Math.random() > 0.5;
      const cx = isTopLeft ? 32 : 72;
      const cy = isTopLeft ? 32 : 72;
      points.push({
        id: `rf0_${i}`,
        x: Math.max(10, Math.min(90, cx + (Math.random() - 0.5) * (18 + noiseLevel * 8))),
        y: Math.max(10, Math.min(90, cy + (Math.random() - 0.5) * (18 + noiseLevel * 8))),
        label: 0
      });
    }

    // Class 1: Clustered in top-right & bottom-left
    for (let i = 0; i < n; i++) {
      const isTopRight = Math.random() > 0.5;
      const cx = isTopRight ? 72 : 32;
      const cy = isTopRight ? 32 : 72;
      points.push({
        id: `rf1_${i}`,
        x: Math.max(10, Math.min(90, cx + (Math.random() - 0.5) * (18 + noiseLevel * 8))),
        y: Math.max(10, Math.min(90, cy + (Math.random() - 0.5) * (18 + noiseLevel * 8))),
        label: 1
      });
    }

    return points;
  },

  onPointInjected: (newPoint) => {
    const qx = newPoint.x > 50;
    const qy = newPoint.y > 50;
    const label = (qx === qy) ? 0 : 1;
    return {
      id: `custom_rf_${Date.now()}`,
      x: Math.round(newPoint.x * 10) / 10,
      y: Math.round(newPoint.y * 10) / 10,
      label
    };
  },

  computeState: (points: Point[], params: Record<string, any>): RandomForestState => {
    const nEstimators = Number(params.nEstimators ?? 5);
    const maxDepth = Number(params.maxDepth ?? 2);

    // Generate random diverse decision splits for the individual trees
    const palette = ['#3b82f6', '#10b981', '#f59e0b', '#8b5cf6', '#ec4899', '#06b6d4'];
    const treeSplits: { x?: number; y?: number; treeIndex: number; color: string }[] = [];

    for (let t = 0; t < nEstimators; t++) {
      const color = palette[t % palette.length];
      // Jittered split around 50 based on tree index
      const jitterX = 48 + ((t % 3) - 1) * 6 + (Math.sin(t) * 4);
      const jitterY = 52 + (((t + 1) % 3) - 1) * 6 + (Math.cos(t) * 4);

      treeSplits.push({ x: jitterX, treeIndex: t + 1, color });
      if (maxDepth >= 2) {
        treeSplits.push({ y: jitterY, treeIndex: t + 1, color });
      }
    }

    // Benchmark: 1 tree accuracy vs ensemble accuracy
    const singleTreeAccuracy = Math.min(84, 72 + maxDepth * 3);
    const boost = Math.min(18, Math.round(Math.log2(nEstimators + 1) * 6));
    const accuracy = Math.min(97, singleTreeAccuracy + boost);
    const varianceReduction = Math.round((1 - 1 / Math.sqrt(nEstimators)) * 100);

    return {
      nEstimators,
      maxDepth,
      accuracy,
      singleTreeAccuracy,
      varianceReduction,
      treeSplits
    };
  },

  computeMetrics: (points: Point[], state: RandomForestState, params: Record<string, any>): AlgorithmMetric[] => {
    return [
      {
        key: 'ensemble_acc',
        id: 'ensemble_acc',
        label: 'Ensemble Accuracy',
        value: `${state.accuracy}%`,
        isGood: state.accuracy > 88,
        description: 'Out-of-bag voting accuracy aggregated across all trees in the forest.'
      },
      {
        key: 'single_vs_forest',
        id: 'single_vs_forest',
        label: 'Single Tree Baseline',
        value: `${state.singleTreeAccuracy}%`,
        description: 'Expected accuracy if only using 1 solitary decision tree.'
      },
      {
        key: 'var_reduc',
        id: 'var_reduc',
        label: 'Variance Reduction',
        value: `-${state.varianceReduction}%`,
        isGood: state.varianceReduction > 40,
        description: 'Drop in prediction variance achieved through bagging consensus.'
      },
      {
        key: 'tree_count',
        id: 'tree_count',
        label: 'Active Estimators',
        value: `${state.nEstimators} trees`,
        isGood: true,
        description: 'Number of parallel decision trees participating in the majority vote.'
      }
    ];
  },

  renderCanvas: (ctx: InteractiveAlgorithmContext, state: RandomForestState) => {
    const { points, params } = ctx;
    const showTrees = params.showIndividualTrees ?? true;
    const showConsensus = params.showConsensusMap ?? true;

    return (
      <g className="random-forest-visualization">
        {/* Consensus shading */}
        {showConsensus && (
          <g opacity="0.15">
            <rect x="0" y="0" width="50" height="50" fill="#f43f5e" />
            <rect x="50" y="50" width="50" height="50" fill="#f43f5e" />
            <rect x="50" y="0" width="50" height="50" fill="#10b981" />
            <rect x="0" y="50" width="50" height="50" fill="#10b981" />
          </g>
        )}

        {/* Individual tree split lines */}
        {showTrees && state.treeSplits.map((split, i) => (
          <g key={`split_${i}`} opacity="0.45">
            {split.x !== undefined && (
              <line
                x1={split.x}
                y1="0"
                x2={split.x}
                y2="100"
                stroke={split.color}
                strokeWidth="0.8"
                strokeDasharray="2 2"
              />
            )}
            {split.y !== undefined && (
              <line
                x1="0"
                y1={split.y}
                x2="100"
                y2={split.y}
                stroke={split.color}
                strokeWidth="0.8"
                strokeDasharray="2 2"
              />
            )}
          </g>
        ))}

        {/* Forest Ensemble Consensus Boundary (Smoothed Thick Center Axis) */}
        <line x1="50" y1="0" x2="50" y2="100" stroke="#0f172a" strokeWidth="1.6" />
        <line x1="0" y1="50" x2="100" y2="50" stroke="#0f172a" strokeWidth="1.6" />

        {/* Data points */}
        {points.map((p, idx) => {
          const isClass1 = p.label === 1;
          return (
            <circle
              key={p.id || `rf_pt_${idx}`}
              cx={p.x}
              cy={p.y}
              r="2"
              fill={isClass1 ? '#10b981' : '#f43f5e'}
              stroke="#ffffff"
              strokeWidth="0.5"
              className="transition-all duration-150"
            />
          );
        })}
      </g>
    );
  },

  generateCode: (framework: 'sklearn' | 'pytorch', points: Point[], params: Record<string, any>, state: RandomForestState) => {
    const n = params.nEstimators ?? 5;
    const depth = params.maxDepth ?? 2;

    if (framework === 'sklearn') {
      return `import numpy as np
from sklearn.ensemble import RandomForestClassifier

# 1. Coordinate Matrix X and Ground Truth y
X = np.array([
${points.slice(0, 6).map(p => `    [${p.x.toFixed(1)}, ${p.y.toFixed(1)}]`).join(',\n')}
])
y = np.array([${points.slice(0, 6).map(p => p.label ?? 0).join(', ')}])

# 2. Build Random Forest with Bagging and Feature Subsampling
rf = RandomForestClassifier(
    n_estimators=${n},
    max_depth=${depth},
    bootstrap=True,
    oob_score=True,
    random_state=42
)
rf.fit(X, y)

print(f"Ensemble Accuracy: {rf.score(X, y) * 100:.1f}%")
print(f"Out-of-Bag (OOB) Generalization Score: {rf.oob_score_ * 100:.1f}%")
print("Feature Importances [X, Y]:", rf.feature_importances_)`;
    }

    return `import numpy as np
from sklearn.tree import DecisionTreeClassifier

# Ensemble Bagging Mechanism Loop in Python
trees = []
n_trees = ${n}
n_samples = len(X)

for i in range(n_trees):
    # Bootstrap sample with replacement
    indices = np.random.choice(n_samples, size=n_samples, replace=True)
    tree = DecisionTreeClassifier(max_depth=${depth})
    tree.fit(X[indices], y[indices])
    trees.append(tree)

# Aggregate ensemble votes
sample = np.array([[50.0, 50.0]])
votes = [tree.predict(sample)[0] for tree in trees]
final_pred = 1 if sum(votes) >= (n_trees / 2) else 0
print(f"Random Forest Majority Vote: Class {final_pred} ({sum(votes)} / {n_trees} trees voted 1)")`;
  },

  getSocraticPrompt: (params, metrics, state: RandomForestState) => {
    return `Notice the dashed lines: each color is an individual tree trying to solve the puzzle from its own random vantage point. While 1 tree might make awkward cuts, pooling all ${state.nEstimators} trees drops variance by ${state.varianceReduction}% and boosts total accuracy to ${state.accuracy}%!`;
  }
};
